Compatibility with C99 standard
RTimothyEdwards/magic pull request #191
Opened 2022-10-10 11:11 UTC by just22

Dear Tim,

This diff makes the code (mostly) C99-compatible, enabling to compile it without the -Wno-error=implicit-function-declaration flag. This way, Magic becomes usable on arm64 architectures, specifically on Apple computers with M1/M2 SoC.

The diff is gigantic (more than 150 files modified), but rather simple; I marked each modification with the `/* C99 compat */` comment, to make it easier to review even after committing.

This addresses (and should resolve) #69; I lightly tested Magic on a M1 Macbook and can confirm that all the segmentation faults I was experiencing before have gone away; in particular, I'm now able to compile the Skywater-130 PDK using open_pdks scripts.

Please let me know in case of any doubt.

Cheers

--
Alessandro

2022-10-19 09:34 UTC, just22 commented
Hello Tim,

Any comments on this PR?

Cheers

--
Alessandro

2022-10-21 20:44 UTC, RTimothyEdwards commented
Yes, I'm way behind on dealing with pull requests.  Give me a few more days.

2022-10-22 18:37 UTC, donn commented
@just22 I'd advise adding `-Werror=implicit-function-declaration` to the compiler flags just so future implicit declarations error out on GCC as well.

2022-10-23 18:08 UTC, just22 commented
@donn Seconded. But I let Tim comment on that and decide where to enforce the flag.

Cheers

--
Alessandro

2022-10-24 15:59 UTC, RTimothyEdwards requested changes
Okay, finally getting around to looking at this.
Very valuable code fixes. . . something that I have balked at for years because it requires changes to 150 files!
Anyway, it all looks good except for the following four items:
1) grTkCommon.c:  There should not be references to OpenGL here, so no need to include anything from OpenGL.  Where is that dependency coming from?  At very least, if it is required, it should be wrapped in `#ifdef OGL . . . #endif` (try compiling without OpenGL support to see what breaks).
2) grTkCommon.c:  I think the calls to `panic()` were inadvertently copied from some code example using them.  I'd rather see the `panic()` calls replaced than to add an include for `mach/mach.h`.  Probably `panic()` should just be replaced with `TxError()` to print the error, followed by `MainExit()` to exit somewhat more gracefully.  At very least, it should be `Tcl_Panic()` and not `panic()`.
3) textioInt.h:  Any routine or variable with `Tcl_` in front should be wrapped in `#ifdef MAGIC_WRAPPER . . . #endif`.  Try compiling without Tcl/Tk support and see what breaks.
4) graphicsInt.h:  Any variable containing "cairo" should be wrapped in `#ifdef CAIRO . . . #endif`.  Try compiling without cairo graphics support to see what breaks.

2022-10-24 16:03 UTC, RTimothyEdwards commented
@donn, @just22 :  I have no issue with having `-Werror=implicit-function-declaration` in the build flags, once it no longer stops magic from compiling.

2022-10-29 04:30 UTC, just22 commented
Dear Tim,

Thanks a lot for your comments and sorry for the late reply, but applying your suggestions has been more complex than expected, since disabling TCL support revealed a bunch of further implicit functions declarations to fix.

Now I have reviewed the compile phase with and without TCL support, with and without CAIRO support, with and without OGL support and with and without X support: all looks good.

Please review all new commits and let me know.

Note: I didn't add `-Werror=implicit-function-declaration` to the build flags: I let you do that, once you're convinced that the code compiles in each and every case.

Cheers

--
Alessandro

2022-10-29 13:32 UTC, RTimothyEdwards approved these changes
This looks good now;  I'm going to try it out, and then push if it all looks good.

2022-10-29 14:06 UTC, merged

2022-10-29 14:08 UTC, RTimothyEdwards commented
@just22 :  I merged this code, then found a few errors on my end and fixed them, and then worked on a handful of warnings that were exposed (previously buried among the slew of implicit function declaration warnings).  I then went ahead and added in the "-Werror=implicit-function-declaration" to the CFLAGS in the configuration script.  Please test the resulting code at your convenience.  And thanks for the hard work!  (And any time you feel like tackling "implicit-int". . . )