add wasm target
RTimothyEdwards/magic pull request #256
Opened 2023-07-11 20:29 UTC by proppy

- add new `asmjs-unknown-emscripten` target
- add `defined(EMSCRIPTEN)` guards
- use `va_list` for variadic function call forwarding
- fix fatal function arguments inconsistency
- add `simple_build_wasm` CI job and store main `magic` wasm bundle as an artefact

Note: currently building with `--without-cairo --without-opengl --without-x --disable-readline` and bundle is already quite big (10M), any idea on how to trim things further?

/cc @urish since this might be relevant for https://github.com/wokwi/siliwiz

2023-07-11 20:41 UTC, RTimothyEdwards requested changes
Looks good except that it looks like you missed having TxError() call TxErrorV().  Unless I'm missing something, it is just running va_start() and va_end() and then returning.

2023-07-11 20:43 UTC, proppy commented
> Looks good except that it looks like you missed having TxError() call TxErrorV(). Unless I'm missing something, it is just running va_start() and va_end() and then returning.

Good catch! Fixed :)

2023-07-11 20:44 UTC, RTimothyEdwards approved these changes
Looks good to me.

2023-07-11 20:46 UTC, proppy commented
@RTimothyEdwards any ideas on how to trim the bundle further? (any other thing we could disable?)

2023-07-11 20:47 UTC, RTimothyEdwards commented
I would not consider 10M very big at all for something as expansive as Magic.  If you are building without graphics, then a lot of the files in the target install `lib/magic/sys/` directory are not needed, including the vector fonts and the default tech files.  I don't think that saves you very much space, though.

2023-07-11 20:52 UTC, proppy commented
@RTimothyEdwards would building `libmagic` rather than `magic`'s `main` save anything?

2023-07-11 20:52 UTC, RTimothyEdwards commented
Pulled and merged (in opencircuitdesign.com).

2023-07-11 20:53 UTC, proppy commented
@RTimothyEdwards thanks as always (and we missed you this year at FSiC!)

2023-07-11 20:56 UTC, RTimothyEdwards commented
@proppy :  No, I don't think `libmagic` will do anything meaningful.
What is the main contributor to the size of your bundle?  The shared object library?

(Yeah, sorry I couldn't make FSiC.  I missed seeing all my European (and Asian) friends.  I will try to make it a regular yearly habit, and this year should be just a one-off exception.)

2023-07-12 05:56 UTC, proppy commented
@RTimothyEdwards PTAL, added https://github.com/RTimothyEdwards/magic/pull/256/commits/26d2ceb77fd7622e06691e2f76baddce9110d0ca which fix a warning/error I got at runtime when testing the bundle (let me know if you'd prefer a separate PR since you already pulled on opencircuitdesign.com).

2023-07-12 14:02 UTC, RTimothyEdwards commented
@proppy :  Yes, actually I would like that as a separate PR, although I can also just manually fix it, as that's probably less involved than making a new PR.

2023-07-12 16:06 UTC, closed without merging

2023-07-12 16:06 UTC, proppy commented
Closing since this is merged, will send another PR for the fixups.